import { configApp } from '@adonisjs/eslint-config'

// The dashboard has its own ESLint setup (dashboard/eslint.config.js); public/ is build output;
// database/schema.ts is regenerated by every `node ace migration:*` and never hand-edited.
export default configApp({ ignores: ['dashboard/**', 'public/**', 'database/schema.ts'] })
