/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  ApAgents: () => import('#controllers/ap_agents_controller'),
  ApJoinTokens: () => import('#controllers/ap_join_tokens_controller'),
  Collectors: () => import('#controllers/collectors_controller'),
  Destinations: () => import('#controllers/destinations_controller'),
  DeviceLabels: () => import('#controllers/device_labels_controller'),
  Devices: () => import('#controllers/devices_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Router: () => import('#controllers/router_controller'),
  Services: () => import('#controllers/services_controller'),
  Settings: () => import('#controllers/settings_controller'),
  Setup: () => import('#controllers/setup_controller'),
  Usage: () => import('#controllers/usage_controller'),
  Users: () => import('#controllers/users_controller'),
  Wifi: () => import('#controllers/wifi_controller'),
}
