/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  AgentSockets: () => import('#controllers/agent_sockets_controller'),
  ApAgents: () => import('#controllers/ap_agents_controller'),
  ApJoinTokens: () => import('#controllers/ap_join_tokens_controller'),
  Collectors: () => import('#controllers/collectors_controller'),
  Destinations: () => import('#controllers/destinations_controller'),
  DeviceLabels: () => import('#controllers/device_labels_controller'),
  Devices: () => import('#controllers/devices_controller'),
  GatewayNames: () => import('#controllers/gateway_names_controller'),
  GatewayObservations: () => import('#controllers/gateway_observations_controller'),
  GatewayNetworks: () => import('#controllers/gateway_networks_controller'),
  GatewaySettings: () => import('#controllers/gateway_settings_controller'),
  Gateways: () => import('#controllers/gateways_controller'),
  Infra: () => import('#controllers/infra_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  PortalApiClients: () => import('#controllers/portal_api_clients_controller'),
  PortalAuthorizations: () => import('#controllers/portal_authorizations_controller'),
  PortalGrants: () => import('#controllers/portal_grants_controller'),
  PortalPortals: () => import('#controllers/portal_portals_controller'),
  PortalTemplates: () => import('#controllers/portal_templates_controller'),
  PortalUsers: () => import('#controllers/portal_users_controller'),
  PortalVouchers: () => import('#controllers/portal_vouchers_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Qos: () => import('#controllers/qos_controller'),
  Router: () => import('#controllers/router_controller'),
  Services: () => import('#controllers/services_controller'),
  Settings: () => import('#controllers/settings_controller'),
  Setup: () => import('#controllers/setup_controller'),
  Usage: () => import('#controllers/usage_controller'),
  Users: () => import('#controllers/users_controller'),
  Version: () => import('#controllers/version_controller'),
  Wifi: () => import('#controllers/wifi_controller'),
}
