/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class ApJoinTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'createdByUserId', 'expiresAt', 'id', 'label', 'lastUsedAt', 'maxUses', 'revokedAt', 'tokenEncrypted', 'tokenHash', 'tokenPrefix', 'updatedAt', 'useCount'] as const
  $columns = ApJoinTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdByUserId: number | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare label: string | null
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare maxUses: number | null
  @column.dateTime()
  declare revokedAt: DateTime | null
  @column()
  declare tokenEncrypted: string
  @column()
  declare tokenHash: string
  @column()
  declare tokenPrefix: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare useCount: number
}

export class ApSystemBuckets5MSchema extends BaseModel {
  static $columns = ['apId', 'avgLoad1', 'avgLoad15', 'avgLoad5', 'maxConntrackEntries', 'maxConntrackLimit', 'maxMemAvailable', 'maxMemTotal', 'maxUptimeSeconds', 'samples', 'slotStart', 'updatedAt'] as const
  $columns = ApSystemBuckets5MSchema.$columns
  @column({ isPrimary: true })
  declare apId: number
  @column()
  declare avgLoad1: number | null
  @column()
  declare avgLoad15: number | null
  @column()
  declare avgLoad5: number | null
  @column()
  declare maxConntrackEntries: number | null
  @column()
  declare maxConntrackLimit: number | null
  @column()
  declare maxMemAvailable: bigint | number | null
  @column()
  declare maxMemTotal: bigint | number | null
  @column()
  declare maxUptimeSeconds: number | null
  @column()
  declare samples: number
  @column.dateTime()
  declare slotStart: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ApSystemLatestSchema extends BaseModel {
  static $columns = ['apId', 'conntrackEntries', 'conntrackLimit', 'load1', 'load15', 'load5', 'memAvailable', 'memTotal', 'recordedAt', 'uptimeSeconds'] as const
  $columns = ApSystemLatestSchema.$columns
  @column({ isPrimary: true })
  declare apId: number
  @column()
  declare conntrackEntries: number | null
  @column()
  declare conntrackLimit: number | null
  @column()
  declare load1: number | null
  @column()
  declare load15: number | null
  @column()
  declare load5: number | null
  @column()
  declare memAvailable: bigint | number | null
  @column()
  declare memTotal: bigint | number | null
  @column.dateTime()
  declare recordedAt: DateTime
  @column()
  declare uptimeSeconds: number | null
}

export class ApSystemSnapshotSchema extends BaseModel {
  static $columns = ['apId', 'conntrackEntries', 'conntrackLimit', 'id', 'load1', 'load15', 'load5', 'memAvailable', 'memTotal', 'recordedAt', 'uptimeSeconds'] as const
  $columns = ApSystemSnapshotSchema.$columns
  @column()
  declare apId: number
  @column()
  declare conntrackEntries: number | null
  @column()
  declare conntrackLimit: number | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare load1: number | null
  @column()
  declare load15: number | null
  @column()
  declare load5: number | null
  @column()
  declare memAvailable: bigint | number | null
  @column()
  declare memTotal: bigint | number | null
  @column.dateTime()
  declare recordedAt: DateTime
  @column()
  declare uptimeSeconds: number | null
}

export class AsnCacheSchema extends BaseModel {
  static $columns = ['asn', 'checkedAt', 'createdAt', 'error', 'id', 'ipAddress', 'org', 'prefix', 'updatedAt'] as const
  $columns = AsnCacheSchema.$columns
  @column()
  declare asn: number | null
  @column.dateTime()
  declare checkedAt: DateTime
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare error: string | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare ipAddress: string
  @column()
  declare org: string | null
  @column()
  declare prefix: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CollectorSchema extends BaseModel {
  static $columns = ['announcedBaseUrl', 'apiKeyFingerprint', 'baseUrl', 'captureInterface', 'createdAt', 'enabled', 'hostname', 'id', 'instanceId', 'lastAnnounceAt', 'lastSeenAt', 'lifecycle', 'name', 'pollIntervalSeconds', 'source', 'transport', 'updatedAt', 'version'] as const
  $columns = CollectorSchema.$columns
  @column()
  declare announcedBaseUrl: string | null
  @column()
  declare apiKeyFingerprint: string | null
  @column()
  declare baseUrl: string | null
  @column()
  declare captureInterface: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare enabled: boolean
  @column()
  declare hostname: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare instanceId: string | null
  @column.dateTime()
  declare lastAnnounceAt: DateTime | null
  @column.dateTime()
  declare lastSeenAt: DateTime | null
  @column()
  declare lifecycle: string
  @column()
  declare name: string
  @column()
  declare pollIntervalSeconds: number
  @column()
  declare source: string
  @column()
  declare transport: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare version: string | null
}

export class DeviceDestinationBucketsHourlySchema extends BaseModel {
  static $columns = ['bytesIn', 'bytesOut', 'category', 'collectorId', 'hourStart', 'mac', 'packetsIn', 'packetsOut', 'peerIp', 'protocol', 'serverName', 'updatedAt'] as const
  $columns = DeviceDestinationBucketsHourlySchema.$columns
  @column()
  declare bytesIn: bigint | number
  @column()
  declare bytesOut: bigint | number
  @column()
  declare category: string
  @column({ isPrimary: true })
  declare collectorId: number
  @column.dateTime()
  declare hourStart: DateTime
  @column()
  declare mac: string
  @column()
  declare packetsIn: bigint | number
  @column()
  declare packetsOut: bigint | number
  @column()
  declare peerIp: string
  @column()
  declare protocol: string
  @column()
  declare serverName: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class DeviceIdentitySchema extends BaseModel {
  static $columns = ['collectorId', 'createdAt', 'firstSeenAt', 'id', 'ips', 'lastSeenAt', 'mac', 'primaryIp', 'updatedAt'] as const
  $columns = DeviceIdentitySchema.$columns
  @column()
  declare collectorId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare firstSeenAt: DateTime | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare ips: string
  @column.dateTime()
  declare lastSeenAt: DateTime | null
  @column()
  declare mac: string
  @column()
  declare primaryIp: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class DeviceLabelSchema extends BaseModel {
  static $columns = ['connection', 'createdAt', 'deviceType', 'id', 'mac', 'name', 'notes', 'tags', 'updatedAt', 'updatedByUserId'] as const
  $columns = DeviceLabelSchema.$columns
  @column()
  declare connection: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare deviceType: string | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare mac: string
  @column()
  declare name: string | null
  @column()
  declare notes: string | null
  @column()
  declare tags: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare updatedByUserId: number | null
}

export class DevicePeerBucketsHourlySchema extends BaseModel {
  static $columns = ['bytesIn', 'bytesOut', 'collectorId', 'hourStart', 'mac', 'peerIp', 'scope', 'updatedAt'] as const
  $columns = DevicePeerBucketsHourlySchema.$columns
  @column()
  declare bytesIn: bigint | number
  @column()
  declare bytesOut: bigint | number
  @column({ isPrimary: true })
  declare collectorId: number
  @column.dateTime()
  declare hourStart: DateTime
  @column()
  declare mac: string
  @column()
  declare peerIp: string
  @column()
  declare scope: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class DeviceProtocolBucketSchema extends BaseModel {
  static $columns = ['bucketStart', 'bytesIn', 'bytesOut', 'collectorId', 'createdAt', 'id', 'mac', 'packetsIn', 'packetsOut', 'protocol', 'updatedAt'] as const
  $columns = DeviceProtocolBucketSchema.$columns
  @column.dateTime()
  declare bucketStart: DateTime
  @column()
  declare bytesIn: bigint | number
  @column()
  declare bytesOut: bigint | number
  @column()
  declare collectorId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare mac: string
  @column()
  declare packetsIn: bigint | number
  @column()
  declare packetsOut: bigint | number
  @column()
  declare protocol: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class DeviceProtocolBuckets5MSchema extends BaseModel {
  static $columns = ['bytesIn', 'bytesOut', 'collectorId', 'mac', 'packetsIn', 'packetsOut', 'protocol', 'slotStart', 'updatedAt'] as const
  $columns = DeviceProtocolBuckets5MSchema.$columns
  @column()
  declare bytesIn: bigint | number
  @column()
  declare bytesOut: bigint | number
  @column({ isPrimary: true })
  declare collectorId: number
  @column()
  declare mac: string
  @column()
  declare packetsIn: bigint | number
  @column()
  declare packetsOut: bigint | number
  @column()
  declare protocol: string
  @column.dateTime()
  declare slotStart: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class DeviceProtocolBucketsDailySchema extends BaseModel {
  static $columns = ['bytesIn', 'bytesOut', 'collectorId', 'dayStart', 'mac', 'packetsIn', 'packetsOut', 'protocol', 'updatedAt'] as const
  $columns = DeviceProtocolBucketsDailySchema.$columns
  @column()
  declare bytesIn: bigint | number
  @column()
  declare bytesOut: bigint | number
  @column({ isPrimary: true })
  declare collectorId: number
  @column.dateTime()
  declare dayStart: DateTime
  @column()
  declare mac: string
  @column()
  declare packetsIn: bigint | number
  @column()
  declare packetsOut: bigint | number
  @column()
  declare protocol: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class DeviceProtocolBucketsHourlySchema extends BaseModel {
  static $columns = ['bytesIn', 'bytesOut', 'collectorId', 'hourStart', 'mac', 'packetsIn', 'packetsOut', 'protocol', 'updatedAt'] as const
  $columns = DeviceProtocolBucketsHourlySchema.$columns
  @column()
  declare bytesIn: bigint | number
  @column()
  declare bytesOut: bigint | number
  @column({ isPrimary: true })
  declare collectorId: number
  @column.dateTime()
  declare hourStart: DateTime
  @column()
  declare mac: string
  @column()
  declare packetsIn: bigint | number
  @column()
  declare packetsOut: bigint | number
  @column()
  declare protocol: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class DeviceServiceBuckets5MSchema extends BaseModel {
  static $columns = ['bytesReceived', 'bytesServed', 'collectorId', 'mac', 'packetsReceived', 'packetsServed', 'protocol', 'serverName', 'slotStart', 'updatedAt'] as const
  $columns = DeviceServiceBuckets5MSchema.$columns
  @column()
  declare bytesReceived: bigint | number
  @column()
  declare bytesServed: bigint | number
  @column({ isPrimary: true })
  declare collectorId: number
  @column()
  declare mac: string
  @column()
  declare packetsReceived: bigint | number
  @column()
  declare packetsServed: bigint | number
  @column()
  declare protocol: string
  @column()
  declare serverName: string
  @column.dateTime()
  declare slotStart: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class DeviceServiceBucketsHourlySchema extends BaseModel {
  static $columns = ['bytesReceived', 'bytesServed', 'collectorId', 'hourStart', 'mac', 'packetsReceived', 'packetsServed', 'protocol', 'serverName', 'updatedAt'] as const
  $columns = DeviceServiceBucketsHourlySchema.$columns
  @column()
  declare bytesReceived: bigint | number
  @column()
  declare bytesServed: bigint | number
  @column({ isPrimary: true })
  declare collectorId: number
  @column.dateTime()
  declare hourStart: DateTime
  @column()
  declare mac: string
  @column()
  declare packetsReceived: bigint | number
  @column()
  declare packetsServed: bigint | number
  @column()
  declare protocol: string
  @column()
  declare serverName: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class DeviceTopPeerSchema extends BaseModel {
  static $columns = ['bytesIn', 'bytesOut', 'collectorId', 'id', 'mac', 'peerIp', 'scope', 'updatedAt'] as const
  $columns = DeviceTopPeerSchema.$columns
  @column()
  declare bytesIn: bigint | number
  @column()
  declare bytesOut: bigint | number
  @column()
  declare collectorId: number
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare mac: string
  @column()
  declare peerIp: string
  @column()
  declare scope: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class DeviceTrafficBucketSchema extends BaseModel {
  static $columns = ['bucketStart', 'bytesIn', 'bytesInLan', 'bytesInWan', 'bytesOut', 'bytesOutLan', 'bytesOutWan', 'collectorId', 'createdAt', 'id', 'mac', 'packetsIn', 'packetsInLan', 'packetsInWan', 'packetsOut', 'packetsOutLan', 'packetsOutWan', 'updatedAt'] as const
  $columns = DeviceTrafficBucketSchema.$columns
  @column.dateTime()
  declare bucketStart: DateTime
  @column()
  declare bytesIn: bigint | number
  @column()
  declare bytesInLan: bigint | number
  @column()
  declare bytesInWan: bigint | number
  @column()
  declare bytesOut: bigint | number
  @column()
  declare bytesOutLan: bigint | number
  @column()
  declare bytesOutWan: bigint | number
  @column()
  declare collectorId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare mac: string
  @column()
  declare packetsIn: bigint | number
  @column()
  declare packetsInLan: bigint | number
  @column()
  declare packetsInWan: bigint | number
  @column()
  declare packetsOut: bigint | number
  @column()
  declare packetsOutLan: bigint | number
  @column()
  declare packetsOutWan: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class DeviceTrafficBuckets5MSchema extends BaseModel {
  static $columns = ['bytesIn', 'bytesInLan', 'bytesInWan', 'bytesOut', 'bytesOutLan', 'bytesOutWan', 'collectorId', 'mac', 'packetsIn', 'packetsInLan', 'packetsInWan', 'packetsOut', 'packetsOutLan', 'packetsOutWan', 'slotStart', 'updatedAt'] as const
  $columns = DeviceTrafficBuckets5MSchema.$columns
  @column()
  declare bytesIn: bigint | number
  @column()
  declare bytesInLan: bigint | number
  @column()
  declare bytesInWan: bigint | number
  @column()
  declare bytesOut: bigint | number
  @column()
  declare bytesOutLan: bigint | number
  @column()
  declare bytesOutWan: bigint | number
  @column({ isPrimary: true })
  declare collectorId: number
  @column()
  declare mac: string
  @column()
  declare packetsIn: bigint | number
  @column()
  declare packetsInLan: bigint | number
  @column()
  declare packetsInWan: bigint | number
  @column()
  declare packetsOut: bigint | number
  @column()
  declare packetsOutLan: bigint | number
  @column()
  declare packetsOutWan: bigint | number
  @column.dateTime()
  declare slotStart: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class DeviceTrafficBucketsDailySchema extends BaseModel {
  static $columns = ['bytesIn', 'bytesInLan', 'bytesInWan', 'bytesOut', 'bytesOutLan', 'bytesOutWan', 'collectorId', 'dayStart', 'mac', 'packetsIn', 'packetsInLan', 'packetsInWan', 'packetsOut', 'packetsOutLan', 'packetsOutWan', 'updatedAt'] as const
  $columns = DeviceTrafficBucketsDailySchema.$columns
  @column()
  declare bytesIn: bigint | number
  @column()
  declare bytesInLan: bigint | number
  @column()
  declare bytesInWan: bigint | number
  @column()
  declare bytesOut: bigint | number
  @column()
  declare bytesOutLan: bigint | number
  @column()
  declare bytesOutWan: bigint | number
  @column({ isPrimary: true })
  declare collectorId: number
  @column.dateTime()
  declare dayStart: DateTime
  @column()
  declare mac: string
  @column()
  declare packetsIn: bigint | number
  @column()
  declare packetsInLan: bigint | number
  @column()
  declare packetsInWan: bigint | number
  @column()
  declare packetsOut: bigint | number
  @column()
  declare packetsOutLan: bigint | number
  @column()
  declare packetsOutWan: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class DeviceTrafficBucketsHourlySchema extends BaseModel {
  static $columns = ['bytesIn', 'bytesInLan', 'bytesInWan', 'bytesOut', 'bytesOutLan', 'bytesOutWan', 'collectorId', 'hourStart', 'mac', 'packetsIn', 'packetsInLan', 'packetsInWan', 'packetsOut', 'packetsOutLan', 'packetsOutWan', 'updatedAt'] as const
  $columns = DeviceTrafficBucketsHourlySchema.$columns
  @column()
  declare bytesIn: bigint | number
  @column()
  declare bytesInLan: bigint | number
  @column()
  declare bytesInWan: bigint | number
  @column()
  declare bytesOut: bigint | number
  @column()
  declare bytesOutLan: bigint | number
  @column()
  declare bytesOutWan: bigint | number
  @column({ isPrimary: true })
  declare collectorId: number
  @column.dateTime()
  declare hourStart: DateTime
  @column()
  declare mac: string
  @column()
  declare packetsIn: bigint | number
  @column()
  declare packetsInLan: bigint | number
  @column()
  declare packetsInWan: bigint | number
  @column()
  declare packetsOut: bigint | number
  @column()
  declare packetsOutLan: bigint | number
  @column()
  declare packetsOutWan: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class InfraLinkSchema extends BaseModel {
  static $columns = ['aPortId', 'bPortId', 'createdAt', 'id', 'label', 'medium', 'notes', 'updatedAt'] as const
  $columns = InfraLinkSchema.$columns
  @column()
  declare aPortId: number
  @column()
  declare bPortId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare label: string | null
  @column()
  declare medium: string
  @column()
  declare notes: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class InfraNodeSchema extends BaseModel {
  static $columns = ['apId', 'collectorId', 'createdAt', 'deviceMac', 'height', 'hidden', 'id', 'kind', 'model', 'name', 'notes', 'origin', 'parentId', 'posX', 'posY', 'updatedAt', 'virtual', 'width'] as const
  $columns = InfraNodeSchema.$columns
  @column()
  declare apId: number | null
  @column()
  declare collectorId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare deviceMac: string | null
  @column()
  declare height: number | null
  @column()
  declare hidden: boolean
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare kind: string
  @column()
  declare model: string | null
  @column()
  declare name: string | null
  @column()
  declare notes: string | null
  @column()
  declare origin: string
  @column()
  declare parentId: number | null
  @column()
  declare posX: number | null
  @column()
  declare posY: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare virtual: boolean
  @column()
  declare width: number | null
}

export class InfraPortSchema extends BaseModel {
  static $columns = ['adminUp', 'carrier', 'carrierChanges', 'createdAt', 'duplex', 'hidden', 'id', 'label', 'mac', 'medium', 'missingSince', 'nodeId', 'operstate', 'origin', 'portKey', 'position', 'present', 'reportedAt', 'reportedLabel', 'reportedMedium', 'reportedRole', 'role', 'speedMbps', 'stateChangedAt', 'updatedAt'] as const
  $columns = InfraPortSchema.$columns
  @column()
  declare adminUp: boolean | null
  @column()
  declare carrier: boolean | null
  @column()
  declare carrierChanges: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare duplex: string | null
  @column()
  declare hidden: boolean
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare label: string | null
  @column()
  declare mac: string | null
  @column()
  declare medium: string | null
  @column.dateTime()
  declare missingSince: DateTime | null
  @column()
  declare nodeId: number
  @column()
  declare operstate: string | null
  @column()
  declare origin: string
  @column()
  declare portKey: string
  @column()
  declare position: number
  @column()
  declare present: boolean
  @column.dateTime()
  declare reportedAt: DateTime | null
  @column()
  declare reportedLabel: string | null
  @column()
  declare reportedMedium: string | null
  @column()
  declare reportedRole: string | null
  @column()
  declare role: string | null
  @column()
  declare speedMbps: number | null
  @column.dateTime()
  declare stateChangedAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProtocolCategorySchema extends BaseModel {
  static $columns = ['category', 'protocol', 'updatedAt'] as const
  $columns = ProtocolCategorySchema.$columns
  @column()
  declare category: string
  @column({ isPrimary: true })
  declare protocol: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class RouterSampleSchema extends BaseModel {
  static $columns = ['conntrackEntries', 'conntrackLimit', 'load1', 'memAvailable', 'memTotal', 'recordedAt', 'scrapeMs', 'tcpEstablished', 'wanRxBps', 'wanRxBytes', 'wanTxBps', 'wanTxBytes'] as const
  $columns = RouterSampleSchema.$columns
  @column()
  declare conntrackEntries: number | null
  @column()
  declare conntrackLimit: number | null
  @column()
  declare load1: string | null
  @column()
  declare memAvailable: bigint | number | null
  @column()
  declare memTotal: bigint | number | null
  @column({ isPrimary: true })
  declare recordedAt: DateTime
  @column()
  declare scrapeMs: number | null
  @column()
  declare tcpEstablished: number | null
  @column()
  declare wanRxBps: bigint | number | null
  @column()
  declare wanRxBytes: bigint | number | null
  @column()
  declare wanTxBps: bigint | number | null
  @column()
  declare wanTxBytes: bigint | number | null
}

export class SystemSettingSchema extends BaseModel {
  static $columns = ['key', 'updatedAt'] as const
  $columns = SystemSettingSchema.$columns
  @column({ isPrimary: true })
  declare key: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'mustChangePassword', 'password', 'role', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare mustChangePassword: boolean
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class WifiAccessPointSchema extends BaseModel {
  static $columns = ['agentConnectedAt', 'agentDisconnectedAt', 'agentId', 'agentInfo', 'agentJoinedAt', 'agentLastAddress', 'agentSecretHash', 'agentVersion', 'createdAt', 'enableTwoWayCommands', 'enabled', 'friendlyName', 'id', 'joinTokenId', 'lastSeenAt', 'lastStatus', 'metricsUrl', 'model', 'name', 'nodename', 'openwrtRelease', 'pollIntervalSeconds', 'sshHost', 'sshPort', 'sshPrivateKey', 'sshUsername', 'transport', 'updatedAt'] as const
  $columns = WifiAccessPointSchema.$columns
  @column.dateTime()
  declare agentConnectedAt: DateTime | null
  @column.dateTime()
  declare agentDisconnectedAt: DateTime | null
  @column()
  declare agentId: string | null
  @column()
  declare agentInfo: string | null
  @column.dateTime()
  declare agentJoinedAt: DateTime | null
  @column()
  declare agentLastAddress: string | null
  @column()
  declare agentSecretHash: string | null
  @column()
  declare agentVersion: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare enableTwoWayCommands: boolean
  @column()
  declare enabled: boolean
  @column()
  declare friendlyName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare joinTokenId: number | null
  @column.dateTime()
  declare lastSeenAt: DateTime | null
  @column()
  declare lastStatus: string | null
  @column()
  declare metricsUrl: string | null
  @column()
  declare model: string | null
  @column()
  declare name: string
  @column()
  declare nodename: string | null
  @column()
  declare openwrtRelease: string | null
  @column()
  declare pollIntervalSeconds: number
  @column()
  declare sshHost: string | null
  @column()
  declare sshPort: number
  @column()
  declare sshPrivateKey: string | null
  @column()
  declare sshUsername: string | null
  @column()
  declare transport: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class WifiClientDistributionSchema extends BaseModel {
  static $columns = ['apId', 'band', 'clientCount', 'grainSeconds', 'slotStart', 'updatedAt'] as const
  $columns = WifiClientDistributionSchema.$columns
  @column()
  declare apId: number
  @column()
  declare band: string
  @column()
  declare clientCount: number
  @column({ isPrimary: true })
  declare grainSeconds: number
  @column.dateTime()
  declare slotStart: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class WifiClientTotalSchema extends BaseModel {
  static $columns = ['clientCount', 'grainSeconds', 'slotStart', 'updatedAt'] as const
  $columns = WifiClientTotalSchema.$columns
  @column()
  declare clientCount: number
  @column({ isPrimary: true })
  declare grainSeconds: number
  @column.dateTime()
  declare slotStart: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class WifiCommandAuditSchema extends BaseModel {
  static $columns = ['apId', 'command', 'executedAt', 'executedByUserId', 'id', 'mac', 'params', 'status', 'stderr', 'stdout'] as const
  $columns = WifiCommandAuditSchema.$columns
  @column()
  declare apId: number
  @column()
  declare command: string
  @column.dateTime()
  declare executedAt: DateTime
  @column()
  declare executedByUserId: number | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare mac: string | null
  @column()
  declare params: string | null
  @column()
  declare status: string
  @column()
  declare stderr: string | null
  @column()
  declare stdout: string | null
}

export class WifiInterfaceBucketSchema extends BaseModel {
  static $columns = ['apId', 'band', 'bucketStart', 'bytesIn', 'bytesOut', 'createdAt', 'dropsIn', 'dropsOut', 'errsIn', 'errsOut', 'id', 'ifname', 'packetsIn', 'packetsOut', 'radio', 'ssid', 'updatedAt'] as const
  $columns = WifiInterfaceBucketSchema.$columns
  @column()
  declare apId: number
  @column()
  declare band: string | null
  @column.dateTime()
  declare bucketStart: DateTime
  @column()
  declare bytesIn: bigint | number
  @column()
  declare bytesOut: bigint | number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare dropsIn: bigint | number
  @column()
  declare dropsOut: bigint | number
  @column()
  declare errsIn: bigint | number
  @column()
  declare errsOut: bigint | number
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare ifname: string
  @column()
  declare packetsIn: bigint | number
  @column()
  declare packetsOut: bigint | number
  @column()
  declare radio: string | null
  @column()
  declare ssid: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class WifiInterfaceBuckets5MSchema extends BaseModel {
  static $columns = ['apId', 'band', 'bytesIn', 'bytesOut', 'dropsIn', 'dropsOut', 'errsIn', 'errsOut', 'ifname', 'packetsIn', 'packetsOut', 'radio', 'slotStart', 'ssid', 'updatedAt'] as const
  $columns = WifiInterfaceBuckets5MSchema.$columns
  @column({ isPrimary: true })
  declare apId: number
  @column()
  declare band: string | null
  @column()
  declare bytesIn: bigint | number
  @column()
  declare bytesOut: bigint | number
  @column()
  declare dropsIn: bigint | number
  @column()
  declare dropsOut: bigint | number
  @column()
  declare errsIn: bigint | number
  @column()
  declare errsOut: bigint | number
  @column()
  declare ifname: string
  @column()
  declare packetsIn: bigint | number
  @column()
  declare packetsOut: bigint | number
  @column()
  declare radio: string | null
  @column.dateTime()
  declare slotStart: DateTime
  @column()
  declare ssid: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class WifiInterfaceBucketsDailySchema extends BaseModel {
  static $columns = ['apId', 'band', 'bytesIn', 'bytesOut', 'dayStart', 'dropsIn', 'dropsOut', 'errsIn', 'errsOut', 'ifname', 'packetsIn', 'packetsOut', 'radio', 'ssid', 'updatedAt'] as const
  $columns = WifiInterfaceBucketsDailySchema.$columns
  @column({ isPrimary: true })
  declare apId: number
  @column()
  declare band: string | null
  @column()
  declare bytesIn: bigint | number
  @column()
  declare bytesOut: bigint | number
  @column.dateTime()
  declare dayStart: DateTime
  @column()
  declare dropsIn: bigint | number
  @column()
  declare dropsOut: bigint | number
  @column()
  declare errsIn: bigint | number
  @column()
  declare errsOut: bigint | number
  @column()
  declare ifname: string
  @column()
  declare packetsIn: bigint | number
  @column()
  declare packetsOut: bigint | number
  @column()
  declare radio: string | null
  @column()
  declare ssid: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class WifiInterfaceBucketsHourlySchema extends BaseModel {
  static $columns = ['apId', 'band', 'bytesIn', 'bytesOut', 'dropsIn', 'dropsOut', 'errsIn', 'errsOut', 'hourStart', 'ifname', 'packetsIn', 'packetsOut', 'radio', 'ssid', 'updatedAt'] as const
  $columns = WifiInterfaceBucketsHourlySchema.$columns
  @column({ isPrimary: true })
  declare apId: number
  @column()
  declare band: string | null
  @column()
  declare bytesIn: bigint | number
  @column()
  declare bytesOut: bigint | number
  @column()
  declare dropsIn: bigint | number
  @column()
  declare dropsOut: bigint | number
  @column()
  declare errsIn: bigint | number
  @column()
  declare errsOut: bigint | number
  @column.dateTime()
  declare hourStart: DateTime
  @column()
  declare ifname: string
  @column()
  declare packetsIn: bigint | number
  @column()
  declare packetsOut: bigint | number
  @column()
  declare radio: string | null
  @column()
  declare ssid: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class WifiNetworkBuckets5MSchema extends BaseModel {
  static $columns = ['apId', 'avgNoiseDbm', 'avgQuality', 'avgSignalDbm', 'band', 'ifname', 'maxBitrateKbps', 'samples', 'slotStart', 'ssid', 'updatedAt'] as const
  $columns = WifiNetworkBuckets5MSchema.$columns
  @column({ isPrimary: true })
  declare apId: number
  @column()
  declare avgNoiseDbm: number | null
  @column()
  declare avgQuality: number | null
  @column()
  declare avgSignalDbm: number | null
  @column()
  declare band: string | null
  @column()
  declare ifname: string
  @column()
  declare maxBitrateKbps: number | null
  @column()
  declare samples: number
  @column.dateTime()
  declare slotStart: DateTime
  @column()
  declare ssid: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class WifiNetworkLatestSchema extends BaseModel {
  static $columns = ['apId', 'band', 'bitrateKbps', 'bssid', 'channel', 'frequencyMhz', 'ifname', 'noiseDbm', 'quality', 'radio', 'recordedAt', 'signalDbm', 'ssid'] as const
  $columns = WifiNetworkLatestSchema.$columns
  @column({ isPrimary: true })
  declare apId: number
  @column()
  declare band: string | null
  @column()
  declare bitrateKbps: number | null
  @column()
  declare bssid: string
  @column()
  declare channel: number | null
  @column()
  declare frequencyMhz: number | null
  @column()
  declare ifname: string
  @column()
  declare noiseDbm: number | null
  @column()
  declare quality: number | null
  @column()
  declare radio: string
  @column.dateTime()
  declare recordedAt: DateTime
  @column()
  declare signalDbm: number | null
  @column()
  declare ssid: string
}

export class WifiNetworkSnapshotSchema extends BaseModel {
  static $columns = ['apId', 'band', 'bitrateKbps', 'bssid', 'channel', 'frequencyMhz', 'id', 'ifname', 'noiseDbm', 'quality', 'radio', 'recordedAt', 'signalDbm', 'ssid'] as const
  $columns = WifiNetworkSnapshotSchema.$columns
  @column()
  declare apId: number
  @column()
  declare band: string | null
  @column()
  declare bitrateKbps: number | null
  @column()
  declare bssid: string
  @column()
  declare channel: number | null
  @column()
  declare frequencyMhz: number | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare ifname: string
  @column()
  declare noiseDbm: number | null
  @column()
  declare quality: number | null
  @column()
  declare radio: string
  @column.dateTime()
  declare recordedAt: DateTime
  @column()
  declare signalDbm: number | null
  @column()
  declare ssid: string
}

export class WifiRoamingEventSchema extends BaseModel {
  static $columns = ['detectedAt', 'eventType', 'fromApId', 'fromBand', 'fromIfname', 'fromSsid', 'id', 'mac', 'toApId', 'toBand', 'toIfname', 'toSsid'] as const
  $columns = WifiRoamingEventSchema.$columns
  @column.dateTime()
  declare detectedAt: DateTime
  @column()
  declare eventType: string
  @column()
  declare fromApId: number | null
  @column()
  declare fromBand: string | null
  @column()
  declare fromIfname: string | null
  @column()
  declare fromSsid: string | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare mac: string
  @column()
  declare toApId: number | null
  @column()
  declare toBand: string | null
  @column()
  declare toIfname: string | null
  @column()
  declare toSsid: string | null
}

export class WifiStationBuckets5MSchema extends BaseModel {
  static $columns = ['activeSamples', 'apId', 'avgSignalDbm', 'avgSnrDb', 'band', 'ifname', 'mac', 'maxRxRateKbps', 'maxSignalDbm', 'maxTxRateKbps', 'minSignalDbm', 'samples', 'slotStart', 'ssid', 'updatedAt'] as const
  $columns = WifiStationBuckets5MSchema.$columns
  @column()
  declare activeSamples: number
  @column({ isPrimary: true })
  declare apId: number
  @column()
  declare avgSignalDbm: number | null
  @column()
  declare avgSnrDb: number | null
  @column()
  declare band: string | null
  @column()
  declare ifname: string | null
  @column()
  declare mac: string
  @column()
  declare maxRxRateKbps: number | null
  @column()
  declare maxSignalDbm: number | null
  @column()
  declare maxTxRateKbps: number | null
  @column()
  declare minSignalDbm: number | null
  @column()
  declare samples: number
  @column.dateTime()
  declare slotStart: DateTime
  @column()
  declare ssid: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class WifiStationLatestSchema extends BaseModel {
  static $columns = ['apId', 'band', 'channel', 'expectedThroughputKbps', 'frequencyMhz', 'ifname', 'inactiveMs', 'mac', 'radio', 'recordedAt', 'rxBytes', 'rxPackets', 'rxRateKbps', 'signalDbm', 'snrDb', 'ssid', 'txBytes', 'txPackets', 'txRateKbps'] as const
  $columns = WifiStationLatestSchema.$columns
  @column()
  declare apId: number
  @column()
  declare band: string | null
  @column()
  declare channel: number | null
  @column()
  declare expectedThroughputKbps: number | null
  @column()
  declare frequencyMhz: number | null
  @column()
  declare ifname: string
  @column()
  declare inactiveMs: number | null
  @column({ isPrimary: true })
  declare mac: string
  @column()
  declare radio: string | null
  @column.dateTime()
  declare recordedAt: DateTime
  @column()
  declare rxBytes: bigint | number | null
  @column()
  declare rxPackets: bigint | number | null
  @column()
  declare rxRateKbps: number | null
  @column()
  declare signalDbm: number | null
  @column()
  declare snrDb: number | null
  @column()
  declare ssid: string | null
  @column()
  declare txBytes: bigint | number | null
  @column()
  declare txPackets: bigint | number | null
  @column()
  declare txRateKbps: number | null
}

export class WifiStationSnapshotSchema extends BaseModel {
  static $columns = ['apId', 'band', 'channel', 'expectedThroughputKbps', 'frequencyMhz', 'id', 'ifname', 'inactiveMs', 'mac', 'radio', 'recordedAt', 'rxBytes', 'rxPackets', 'rxRateKbps', 'signalDbm', 'snrDb', 'ssid', 'txBytes', 'txPackets', 'txRateKbps'] as const
  $columns = WifiStationSnapshotSchema.$columns
  @column()
  declare apId: number
  @column()
  declare band: string | null
  @column()
  declare channel: number | null
  @column()
  declare expectedThroughputKbps: number | null
  @column()
  declare frequencyMhz: number | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare ifname: string
  @column()
  declare inactiveMs: number | null
  @column()
  declare mac: string
  @column()
  declare radio: string | null
  @column.dateTime()
  declare recordedAt: DateTime
  @column()
  declare rxBytes: bigint | number | null
  @column()
  declare rxPackets: bigint | number | null
  @column()
  declare rxRateKbps: number | null
  @column()
  declare signalDbm: number | null
  @column()
  declare snrDb: number | null
  @column()
  declare ssid: string | null
  @column()
  declare txBytes: bigint | number | null
  @column()
  declare txPackets: bigint | number | null
  @column()
  declare txRateKbps: number | null
}
