/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type CollectorSummaryTransformer from '#transformers/collector_summary_transformer'
import type CollectorTransformer from '#transformers/collector_transformer'
import type DeviceSummaryTransformer from '#transformers/device_summary_transformer'
import type UserTransformer from '#transformers/user_transformer'
import type WifiAccessPointTransformer from '#transformers/wifi_access_point_transformer'

export namespace Data {
  export type CollectorSummary = InferData<CollectorSummaryTransformer>
  export namespace CollectorSummary {
    export type Variants = InferVariants<CollectorSummaryTransformer>
  }
  export type Collector = InferData<CollectorTransformer>
  export namespace Collector {
    export type Variants = InferVariants<CollectorTransformer>
  }
  export type DeviceSummary = InferData<DeviceSummaryTransformer>
  export namespace DeviceSummary {
    export type Variants = InferVariants<DeviceSummaryTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
  export type WifiAccessPoint = InferData<WifiAccessPointTransformer>
  export namespace WifiAccessPoint {
    export type Variants = InferVariants<WifiAccessPointTransformer>
  }
}
