/*
|--------------------------------------------------------------------------
| Routes file
|--------------------------------------------------------------------------
|
| The routes file is used for defining the HTTP routes.
|
*/

import { access } from 'node:fs/promises'
import { errors } from '@adonisjs/core'
import app from '@adonisjs/core/services/app'
import type { HttpContext } from '@adonisjs/core/http'
import { middleware } from '#start/kernel'
import router from '@adonisjs/core/services/router'
import { controllers } from '#generated/controllers'

/**
 * The setup controller isn't in the auto-generated `controllers` registry
 * yet (regenerated by the dev server on save); declared inline so this
 * routes file remains the source of truth and `npm run typecheck` passes
 * even on a cold checkout.
 */
const SetupController = () => import('#controllers/setup_controller')

/**
 * Same story for the devices controller — added in the poller session.
 * Inline until the next dev-server restart regenerates the registry.
 */
const DevicesController = () => import('#controllers/devices_controller')

/**
 * Settings API lives behind auth + admin and only opens after setup.
 * Inline import for the same generated-registry reason as above.
 */
const SettingsController = () => import('#controllers/settings_controller')
const GatewaySettingsController = () => import('#controllers/gateway_settings_controller')
const WifiController = () => import('#controllers/wifi_controller')
const UsersController = () => import('#controllers/users_controller')
const ServicesController = () => import('#controllers/services_controller')
const DestinationsController = () => import('#controllers/destinations_controller')
const GatewayObservationsController = () => import('#controllers/gateway_observations_controller')
const UsageController = () => import('#controllers/usage_controller')
const RouterController = () => import('#controllers/router_controller')
const ProfileController = () => import('#controllers/profile_controller')
const DeviceLabelsController = () => import('#controllers/device_labels_controller')
const CollectorsController = () => import('#controllers/collectors_controller')
const ApAgentsController = () => import('#controllers/ap_agents_controller')
const ApJoinTokensController = () => import('#controllers/ap_join_tokens_controller')
const AgentSocketsController = () => import('#controllers/agent_sockets_controller')
const InfraController = () => import('#controllers/infra_controller')
const VersionController = () => import('#controllers/version_controller')
const PortalPortalsController = () => import('#controllers/portal_portals_controller')
const PortalTemplatesController = () => import('#controllers/portal_templates_controller')
const PortalVouchersController = () => import('#controllers/portal_vouchers_controller')
const PortalUsersController = () => import('#controllers/portal_users_controller')
const PortalApiClientsController = () => import('#controllers/portal_api_clients_controller')
const PortalGrantsController = () => import('#controllers/portal_grants_controller')
const PortalAuthorizationsController = () => import('#controllers/portal_authorizations_controller')
const QosController = () => import('#controllers/qos_controller')
const GatewaysController = () => import('#controllers/gateways_controller')
const GatewayNamesController = () => import('#controllers/gateway_names_controller')

/**
 * Setup wizard endpoints. INTENTIONALLY outside the requireSetupComplete
 * gate (since they ARE the way to complete setup). `status`, `admin` and
 * `login` are public; once an admin exists, the rest of the wizard requires
 * that admin's bearer token, which `login` hands out again to the step-1
 * credentials while setup is incomplete.
 */
router
  .group(() => {
    router.get('status', [SetupController, 'status']).as('status')
    router.post('admin', [SetupController, 'admin']).as('admin')
    /**
     * Resume an unfinished wizard with the step-1 admin's credentials
     * (409 once setup is complete; rate-limited per address).
     */
    router.post('login', [SetupController, 'login']).as('login')
    router
      .post('instance', [SetupController, 'instance'])
      .as('instance')
      .use([middleware.auth(), middleware.requireAdmin()])
    router
      .post('collector', [SetupController, 'collector'])
      .as('collector')
      .use([middleware.auth(), middleware.requireAdmin()])
    router
      .get('collector/candidates', [SetupController, 'candidates'])
      .as('collector.candidates')
      .use([middleware.auth(), middleware.requireAdmin()])
    router
      .post('collector/skip', [SetupController, 'skipCollector'])
      .as('collector.skip')
      .use([middleware.auth(), middleware.requireAdmin()])
    router
      .post('collector/:id/adopt', [SetupController, 'adopt'])
      .as('collector.adopt')
      .where('id', router.matchers.number())
      .use([middleware.auth(), middleware.requireAdmin()])
  })
  .prefix('/api/v1/setup')
  .as('setup')

/**
 * Controller version and the daemon releases it pairs with. Public and
 * outside the setup gate, like `setup/status`.
 */
router.get('/api/v1/version', [VersionController, 'show']).as('version')

/**
 * Collector self-announcement. INTENTIONALLY outside both `auth` and the
 * requireSetupComplete gate — a router that boots before the wizard has been
 * run must still be able to show up. Everything an announce can do is create
 * or refresh ONE `pending` row; adoption is an explicit admin action under
 * /api/v1/settings/collectors. Declared next to the setup group (outside the
 * gate for the same reason) and before the /api/v1 group so registration
 * order never lets the SPA wildcard at the bottom of this file swallow it.
 */
router
  .post('/api/v1/collectors/announce', [CollectorsController, 'announce'])
  .as('collectors.announce')

/**
 * ap-controller join (docs/ap-controller.md section 2.1). Outside `auth` and
 * the setup gate for the same reason as the announce: the join token in the
 * body is the credential.
 */
router.post('/api/v1/ap-agent/join', [ApAgentsController, 'join']).as('apAgent.join')

/**
 * The device agents' WebSockets. providers/agent_gateway_provider.ts handles
 * the upgrades on the Node server; these routes only see what it does not:
 * an upgrade in the moment after start, before it is attached (503, so the
 * agent retries in seconds instead of backing off for minutes on a 404), and
 * plain GETs (426).
 */
router.get('/api/v1/ap-agent/ws', [AgentSocketsController, 'fallback']).as('apAgent.wsFallback')
router
  .get('/api/v1/collector-agent/ws', [AgentSocketsController, 'fallback'])
  .as('collectorAgent.wsFallback')

/**
 * Normal API surface. Gated behind requireSetupComplete so /auth/login and
 * /account/* return a structured 503 with the next wizard step while the
 * instance hasn't been bootstrapped yet.
 */
router
  .group(() => {
    router
      .group(() => {
        router.post('signup', [controllers.NewAccount, 'store'])
        router.post('login', [controllers.AccessTokens, 'store'])
      })
      .prefix('auth')
      .as('auth')

    router
      .group(() => {
        router.get('profile', [controllers.Profile, 'show'])
        router.patch('password', [ProfileController, 'changePassword'])
        router.post('logout', [controllers.AccessTokens, 'destroy'])
      })
      .prefix('account')
      .as('profile')
      .use(middleware.auth())

    router
      .group(() => {
        router.get('hostname-enrichment', [SettingsController, 'hostnameEnrichment'])
        router.patch('hostname-enrichment', [SettingsController, 'updateHostnameEnrichment'])
        router.get('hostname-enrichment/sources', [SettingsController, 'hostnameEnrichmentSources'])
        router.get('presence', [SettingsController, 'presence']).as('presence')
        router.patch('presence', [SettingsController, 'updatePresence']).as('updatePresence')
        router.get('gateway', [GatewaySettingsController, 'show']).as('gateway')
        router.patch('gateway', [GatewaySettingsController, 'update']).as('updateGateway')
        router
          .get('gateway-observations', [GatewayObservationsController, 'settings'])
          .as('gatewayObservations')
        router
          .patch('gateway-observations', [GatewayObservationsController, 'updateSettings'])
          .as('updateGatewayObservations')
        router.get('qos', [SettingsController, 'qos']).as('qos')
        router.patch('qos', [SettingsController, 'updateQos']).as('updateQos')
        router.get('charts', [SettingsController, 'charts']).as('charts')
        router.patch('charts', [SettingsController, 'updateCharts']).as('updateCharts')
        router.get('wifi-sources', [SettingsController, 'wifiSources'])
        router.post('wifi-sources/probe', [SettingsController, 'probeWifiSourceDraft'])
        router.post('wifi-sources', [SettingsController, 'createWifiSource'])
        router.put('wifi-sources/:id', [SettingsController, 'updateWifiSource'])
        router.delete('wifi-sources/:id', [SettingsController, 'deleteWifiSource'])
        router.post('wifi-sources/:id/probe', [SettingsController, 'probeWifiSource'])
        router
          .post('wifi-sources/:id/agent/ping', [ApAgentsController, 'ping'])
          .as('wifiSources.agentPing')
        router
          .delete('wifi-sources/:id/agent', [ApAgentsController, 'forget'])
          .as('wifiSources.agentForget')

        router.get('ap-join-tokens', [ApJoinTokensController, 'index']).as('apJoinTokens.index')
        router.post('ap-join-tokens', [ApJoinTokensController, 'store']).as('apJoinTokens.store')
        router
          .post('ap-join-tokens/:id/reveal', [ApJoinTokensController, 'reveal'])
          .as('apJoinTokens.reveal')
        router
          .delete('ap-join-tokens/:id', [ApJoinTokensController, 'destroy'])
          .as('apJoinTokens.destroy')
        router.get('ap-agent/install', [ApAgentsController, 'installInfo']).as('apAgent.install')

        router.get('collectors', [CollectorsController, 'index']).as('collectors.index')
        router.post('collectors', [CollectorsController, 'store']).as('collectors.store')
        /**
         * Static segments declared before the `:id` routes, same reason as
         * `labels` in the devices group below.
         */
        router
          .get('collectors/discovery', [CollectorsController, 'discovery'])
          .as('collectors.discovery')
        router
          .patch('collectors/discovery', [CollectorsController, 'updateDiscovery'])
          .as('collectors.updateDiscovery')
        router
          .post('collectors/probe', [CollectorsController, 'probeDraft'])
          .as('collectors.probeDraft')
        router.put('collectors/:id', [CollectorsController, 'update']).as('collectors.update')
        router.delete('collectors/:id', [CollectorsController, 'destroy']).as('collectors.destroy')
        router.post('collectors/:id/probe', [CollectorsController, 'probe']).as('collectors.probe')
        router.post('collectors/:id/adopt', [CollectorsController, 'adopt']).as('collectors.adopt')
        router
          .post('collectors/:id/dismiss', [CollectorsController, 'dismiss'])
          .as('collectors.dismiss')

        router.get('portal', [PortalPortalsController, 'settings']).as('portal')
        router.patch('portal', [PortalPortalsController, 'updateSettings']).as('updatePortal')

        router.get('users', [UsersController, 'index']).as('users.index')
        router.post('users', [UsersController, 'store']).as('users.store')
        router.patch('users/:id/role', [UsersController, 'updateRole']).as('users.updateRole')
        router.delete('users/:id', [UsersController, 'destroy']).as('users.destroy')
      })
      .prefix('settings')
      .as('settings')
      .use([middleware.auth(), middleware.requirePasswordChange(), middleware.requireAdmin()])

    /**
     * Read API for what the poller has captured. All three endpoints are
     * behind `auth` (operator and admin both qualify) so the eventual
     * dashboard can call them with a logged-in user's bearer token
     * without needing service tokens.
     */
    router
      .get('traffic', [DevicesController, 'aggregateTraffic'])
      .as('aggregateTraffic')
      .use([middleware.auth(), middleware.requirePasswordChange()])
    router
      .get('traffic/top', [DevicesController, 'topTraffic'])
      .as('topTraffic')
      .use([middleware.auth(), middleware.requirePasswordChange()])
    router
      .get('protocols', [DevicesController, 'aggregateProtocols'])
      .as('aggregateProtocols')
      .use([middleware.auth(), middleware.requirePasswordChange()])
    router
      .get('protocols/:protocol/devices', [DevicesController, 'aggregateProtocolDevices'])
      .as('aggregateProtocolDevices')
      .use([middleware.auth(), middleware.requirePasswordChange()])
    /**
     * Network-wide "where is the traffic going": top peer IPs (and their
     * ASNs) across every device over a window, from the hourly peer history.
     */
    router
      .get('peers/top', [DevicesController, 'topPeers'])
      .as('topPeers')
      .use([middleware.auth(), middleware.requirePasswordChange()])
    /**
     * "How many GB did my servers push": bytes served per TLS SNI / HTTP
     * Host, from the hourly service history the collector's nDPI path feeds.
     */
    router
      .group(() => {
        router.get('', [ServicesController, 'index']).as('index')
        router.get(':serverName/traffic', [ServicesController, 'traffic']).as('traffic')
      })
      .prefix('services')
      .as('services')
      .use([middleware.auth(), middleware.requirePasswordChange()])

    router
      .get('router', [RouterController, 'index'])
      .as('router')
      .use([middleware.auth(), middleware.requirePasswordChange()])

    /**
     * Collector picker for any signed-in user. The settings list above is
     * admin-only and carries the pollable address; this one is the thin,
     * address-free shape an operator may see.
     */
    router
      .get('collectors', [CollectorsController, 'summary'])
      .as('collectors')
      .use([middleware.auth(), middleware.requirePasswordChange()])

    router
      .group(() => {
        router.get('', [UsageController, 'index']).as('index')
        router.get('intervals', [UsageController, 'intervals']).as('intervals')
      })
      .prefix('usage')
      .as('usage')
      .use([middleware.auth(), middleware.requirePasswordChange()])

    router
      .group(() => {
        router.get('', [DestinationsController, 'index']).as('index')
        router.get(':serverName/traffic', [DestinationsController, 'traffic']).as('traffic')
      })
      .prefix('destinations')
      .as('destinations')
      .use([middleware.auth(), middleware.requirePasswordChange()])

    router
      .group(() => {
        router.get('', [DevicesController, 'index']).as('index')
        /**
         * Operator-supplied names, types, tags and notes. `labels` is a
         * static segment and is declared before the `:mac/…` routes so it
         * can never be read as a MAC. Writes are open to any signed-in
         * user, like the reads around them.
         */
        router.get('labels', [DeviceLabelsController, 'index']).as('labels')
        router.get(':mac/label', [DeviceLabelsController, 'show']).as('label')
        router.patch(':mac/label', [DeviceLabelsController, 'update']).as('updateLabel')
        router.delete(':mac/label', [DeviceLabelsController, 'destroy']).as('destroyLabel')
        router.get(':mac/traffic', [DevicesController, 'traffic']).as('traffic')
        router.get(':mac/peers', [DevicesController, 'peers']).as('peers')
        router.get(':mac/peers/history', [DevicesController, 'peersHistory']).as('peersHistory')
        router.get(':mac/services', [ServicesController, 'device']).as('services')
        router.get(':mac/destinations', [DestinationsController, 'device']).as('destinations')
        router.get(':mac/overview', [DevicesController, 'overview']).as('overview')
        router.get(':mac/presence', [DevicesController, 'presence']).as('presence')
        router.get(':mac/shaping', [DevicesController, 'shaping']).as('shaping')
        router.get(':mac/protocols', [DevicesController, 'protocols']).as('protocols')
        router.get(':mac/network', [GatewayObservationsController, 'deviceNetwork']).as('network')
        /**
         * The device's DHCP reservation and DNS name on the managed gateway
         * (docs/gateway/config-plane.md section 10.3). Reads for any user,
         * writes admin-only.
         */
        router
          .get(':mac/reservation', [GatewayNamesController, 'showReservation'])
          .as('reservation')
        router
          .group(() => {
            router
              .put(':mac/reservation', [GatewayNamesController, 'putReservation'])
              .as('putReservation')
            router
              .delete(':mac/reservation', [GatewayNamesController, 'deleteReservation'])
              .as('deleteReservation')
          })
          .use(middleware.requireAdmin())
      })
      .prefix('devices')
      .as('devices')
      .use([middleware.auth(), middleware.requirePasswordChange()])

    router
      .group(() => {
        router.get('overview', [WifiController, 'overview'])
        router.get('ssids', [WifiController, 'ssids'])
        router.get('ssids/:ssid/clients', [WifiController, 'ssidClients'])
        router.get('ssids/:ssid/throughput', [WifiController, 'ssidThroughput'])
        router.get('clients', [WifiController, 'clients'])
        router.get('clients/history', [WifiController, 'clientsHistory'])
        router.get('clients/:mac', [WifiController, 'client'])
        router.get('clients/:mac/signal', [WifiController, 'clientSignal'])
        router.get('rf', [WifiController, 'rf'])
        router.get('rf/history', [WifiController, 'rfHistory'])
        router.get('aps', [WifiController, 'aps'])
        router.get('aps/throughput', [WifiController, 'apsThroughput'])
        router.get('aps/:id/health', [WifiController, 'apHealth'])
        router
          .group(() => {
            router.post('clients/:mac/kick', [WifiController, 'kickClient'])
            router.post('clients/:mac/steer', [WifiController, 'steerClient'])
            router.post('aps/:id/reboot', [WifiController, 'rebootAp'])
            router.post('aps/:id/locate', [WifiController, 'locateAp'])
          })
          .use(middleware.requireAdmin())
      })
      .prefix('wifi')
      .as('wifi')
      .use([middleware.auth(), middleware.requirePasswordChange()])

    /**
     * Infrastructure view (docs/infrastructure-view.md section 7): the network
     * map's devices, ports and cables. Any signed-in user reads it; the layout
     * is shared work, so every write is admin-only.
     */
    router
      .group(() => {
        router.get('layout', [InfraController, 'layout']).as('layout')
        router.get('state', [InfraController, 'state']).as('state')
        router
          .group(() => {
            router.post('nodes', [InfraController, 'createNode']).as('nodes.store')
            router
              .patch('nodes/:id', [InfraController, 'updateNode'])
              .as('nodes.update')
              .where('id', router.matchers.number())
            router
              .delete('nodes/:id', [InfraController, 'destroyNode'])
              .as('nodes.destroy')
              .where('id', router.matchers.number())
            router
              .post('nodes/:id/bind', [InfraController, 'bindNode'])
              .as('nodes.bind')
              .where('id', router.matchers.number())
            router
              .post('nodes/:id/ports', [InfraController, 'addPorts'])
              .as('nodes.ports.store')
              .where('id', router.matchers.number())
            router
              .patch('ports/:id', [InfraController, 'updatePort'])
              .as('ports.update')
              .where('id', router.matchers.number())
            router
              .delete('ports/:id', [InfraController, 'destroyPort'])
              .as('ports.destroy')
              .where('id', router.matchers.number())
            router.post('links', [InfraController, 'createLink']).as('links.store')
            router
              .patch('links/:id', [InfraController, 'updateLink'])
              .as('links.update')
              .where('id', router.matchers.number())
            router
              .delete('links/:id', [InfraController, 'destroyLink'])
              .as('links.destroy')
              .where('id', router.matchers.number())
            router.put('positions', [InfraController, 'savePositions']).as('positions')
          })
          .use(middleware.requireAdmin())
      })
      .prefix('infra')
      .as('infra')
      .use([middleware.auth(), middleware.requirePasswordChange()])

    /**
     * The gateway's observed runtime state (docs/gateway/observation.md
     * section 7; plan-2-native-sync.md section 5, read part). `:gatewayId` is
     * the collector id of the Gateway agent. Leases, neighbours, interfaces,
     * UPnP and WAN status are for any signed-in user; the rest is admin-only.
     */
    router
      .group(() => {
        router.get(':gatewayId/observation', [GatewayObservationsController, 'overview'])
        router.get(':gatewayId/dhcp/leases', [GatewayObservationsController, 'leases'])
        router.get(':gatewayId/neighbors', [GatewayObservationsController, 'neighbors'])
        router.get(':gatewayId/interfaces', [GatewayObservationsController, 'interfaces'])
        router.get(':gatewayId/upnp', [GatewayObservationsController, 'upnp'])
        router.get(':gatewayId/wan-status', [GatewayObservationsController, 'wanStatus'])
        router
          .group(() => {
            router.get(':gatewayId/system', [GatewayObservationsController, 'system'])
            router.get(':gatewayId/wireguard', [GatewayObservationsController, 'wireguard'])
            router.post(':gatewayId/observe', [GatewayObservationsController, 'observe'])
            router.get(':gatewayId/backups', [GatewayObservationsController, 'backups'])
            router.post(':gatewayId/backups', [GatewayObservationsController, 'createBackup'])
            router
              .get(':gatewayId/backups/:backupId/download', [
                GatewayObservationsController,
                'downloadBackup',
              ])
              .where('backupId', router.matchers.number())
          })
          .use(middleware.requireAdmin())
      })
      .prefix('gateways')
      .as('gatewayObservations')
      .where('gatewayId', router.matchers.number())
      .use([middleware.auth(), middleware.requirePasswordChange()])

    /**
     * Guest portal authorize API (docs/gateway/portal.md section 11.6):
     * outside `auth()`, because its callers are integrations (paid-hotspot
     * integrations such as coin-operated vending boxes) with their own scoped `perch_pa_` tokens;
     * `portalApiAuth` also takes an admin's token. Rate-limited per token,
     * failed tokens per address.
     */
    router
      .group(() => {
        router.post('authorizations', [PortalAuthorizationsController, 'store']).as('store')
        router.get('authorizations/:mac', [PortalAuthorizationsController, 'show']).as('show')
        router
          .delete('authorizations/:mac', [PortalAuthorizationsController, 'destroy'])
          .as('destroy')
      })
      .prefix('portal')
      .as('portal.authorizations')
      .use(middleware.portalApiAuth())

    /**
     * Guest portal (docs/gateway/portal.md section 11). Portals, grants and
     * sessions are readable by any signed-in user; every write, and all of
     * templates, vouchers, portal users and API clients (codes, passwords,
     * tokens), is admin-only.
     */
    router
      .group(() => {
        router.get('portals', [PortalPortalsController, 'index']).as('portals.index')
        router.get('portals/:id', [PortalPortalsController, 'show']).as('portals.show')
        router.get('grants', [PortalGrantsController, 'index']).as('grants.index')
        router.get('sessions', [PortalGrantsController, 'sessions']).as('sessions.index')
        router
          .group(() => {
            router.post('portals', [PortalPortalsController, 'store']).as('portals.store')
            router.patch('portals/:id', [PortalPortalsController, 'update']).as('portals.update')
            router.delete('portals/:id', [PortalPortalsController, 'destroy']).as('portals.destroy')

            router.post('grants/:id/extend', [PortalGrantsController, 'extend']).as('grants.extend')
            router.post('grants/:id/revoke', [PortalGrantsController, 'revoke']).as('grants.revoke')

            router.get('templates', [PortalTemplatesController, 'index']).as('templates.index')
            router.post('templates', [PortalTemplatesController, 'store']).as('templates.store')
            router.get('templates/:id', [PortalTemplatesController, 'show']).as('templates.show')
            router
              .patch('templates/:id', [PortalTemplatesController, 'update'])
              .as('templates.update')
            router
              .delete('templates/:id', [PortalTemplatesController, 'destroy'])
              .as('templates.destroy')
            router
              .post('templates/:id/duplicate', [PortalTemplatesController, 'duplicate'])
              .as('templates.duplicate')
            router
              .get('templates/:id/preview', [PortalTemplatesController, 'preview'])
              .as('templates.preview')
            router
              .put('templates/:id/files/:name', [PortalTemplatesController, 'putFile'])
              .as('templates.files.put')
            router
              .delete('templates/:id/files/:name', [PortalTemplatesController, 'destroyFile'])
              .as('templates.files.destroy')

            router
              .post('voucher-batches', [PortalVouchersController, 'storeBatch'])
              .as('voucherBatches.store')
            router
              .get('voucher-batches', [PortalVouchersController, 'indexBatches'])
              .as('voucherBatches.index')
            router
              .get('voucher-batches/:id', [PortalVouchersController, 'showBatch'])
              .as('voucherBatches.show')
            router
              .get('voucher-batches/:id/codes', [PortalVouchersController, 'codes'])
              .as('voucherBatches.codes')
            router
              .get('voucher-batches/:id/codes.csv', [PortalVouchersController, 'csv'])
              .as('voucherBatches.csv')
            router
              .post('voucher-batches/:id/revoke', [PortalVouchersController, 'revokeBatch'])
              .as('voucherBatches.revoke')
            router
              .delete('voucher-batches/:id', [PortalVouchersController, 'destroyBatch'])
              .as('voucherBatches.destroy')
            router.get('vouchers', [PortalVouchersController, 'index']).as('vouchers.index')
            // Static segment before `vouchers/:id/…`.
            router
              .post('vouchers/lookup', [PortalVouchersController, 'lookup'])
              .as('vouchers.lookup')
            router
              .post('vouchers/:id/revoke', [PortalVouchersController, 'revoke'])
              .as('vouchers.revoke')

            router.get('users', [PortalUsersController, 'index']).as('users.index')
            router.post('users', [PortalUsersController, 'store']).as('users.store')
            router.patch('users/:id', [PortalUsersController, 'update']).as('users.update')
            router
              .put('users/:id/password', [PortalUsersController, 'password'])
              .as('users.password')
            router.delete('users/:id', [PortalUsersController, 'destroy']).as('users.destroy')

            router.get('api-clients', [PortalApiClientsController, 'index']).as('apiClients.index')
            router.post('api-clients', [PortalApiClientsController, 'store']).as('apiClients.store')
            router
              .patch('api-clients/:id', [PortalApiClientsController, 'update'])
              .as('apiClients.update')
            router
              .post('api-clients/:id/rotate', [PortalApiClientsController, 'rotate'])
              .as('apiClients.rotate')
            router
              .delete('api-clients/:id', [PortalApiClientsController, 'destroy'])
              .as('apiClients.destroy')
          })
          .use(middleware.requireAdmin())
      })
      .prefix('portal')
      .as('portal')
      .use([middleware.auth(), middleware.requirePasswordChange()])

    /**
     * Traffic shaping (docs/gateway/qos.md section 5). Every signed-in user
     * reads it (owner decision 16: operators see every cap, bucket and
     * schedule); writes are admin-only and go through the config plane.
     */
    router
      .group(() => {
        router.get('', [QosController, 'overview']).as('overview')
        router.get('devices', [QosController, 'devices']).as('devices.index')
        router.get('wan-queues', [QosController, 'wanQueues']).as('wanQueues.index')
        router.get('policies', [QosController, 'policies']).as('policies.index')
        router.get('groups', [QosController, 'groups']).as('groups.index')
        router.get('assignments', [QosController, 'assignments']).as('assignments.index')
        router.get('schedules', [QosController, 'schedules']).as('schedules.index')
        router
          .group(() => {
            router.post('wan-queues', [QosController, 'createWanQueue']).as('wanQueues.store')
            router
              .patch('wan-queues/:id', [QosController, 'updateWanQueue'])
              .as('wanQueues.update')
              .where('id', router.matchers.number())
            router
              .delete('wan-queues/:id', [QosController, 'destroyWanQueue'])
              .as('wanQueues.destroy')
              .where('id', router.matchers.number())
            for (const [path, name, controller] of [
              ['policies', 'policies', 'Policy'],
              ['groups', 'groups', 'Group'],
              ['assignments', 'assignments', 'Assignment'],
              ['schedules', 'schedules', 'Schedule'],
            ] as const) {
              router.post(path, [QosController, `create${controller}`]).as(`${name}.store`)
              router
                .patch(`${path}/:id`, [QosController, `update${controller}`])
                .as(`${name}.update`)
                .where('id', router.matchers.number())
              router
                .delete(`${path}/:id`, [QosController, `destroy${controller}`])
                .as(`${name}.destroy`)
                .where('id', router.matchers.number())
            }
            router
              .post('assignments/:id/quota/reset', [QosController, 'resetQuota'])
              .as('assignments.resetQuota')
              .where('id', router.matchers.number())
            router.post('pause', [QosController, 'pause']).as('pause')
            router.post('resume', [QosController, 'resume']).as('resume')
          })
          .use(middleware.requireAdmin())
      })
      .prefix('qos')
      .as('qos')
      .use([middleware.auth(), middleware.requirePasswordChange()])

    /**
     * The managed gateway's config plane (docs/gateway/config-plane.md
     * section 10). `:id` is `gateways.id`. Reads for any signed-in user,
     * writes admin-only; entering managed mode and Authoritative Mode ON also
     * take the admin's current password. The observation routes
     * (docs/gateway/observation.md: observation, dhcp/leases, neighbors,
     * interfaces, upnp, wan-status, system, wireguard, observe, backups) share
     * this prefix and are not defined here.
     */
    router
      .group(() => {
        router.get('', [GatewaysController, 'index']).as('index')
        router.get(':id', [GatewaysController, 'show']).as('show')
        router.get(':id/sync-status', [GatewaysController, 'syncStatus']).as('syncStatus')
        router.get(':id/sections', [GatewaysController, 'sections']).as('sections')
        router.get(':id/sections/:perchId', [GatewaysController, 'section']).as('section')
        router.get(':id/draft', [GatewaysController, 'draft']).as('draft')
        router.get(':id/applies', [GatewaysController, 'applies']).as('applies')
        router.get(':id/applies/:applyId', [GatewaysController, 'apply']).as('apply')
        router.get(':id/revisions', [GatewaysController, 'revisions']).as('revisions')
        router
          .get(':id/revisions/:number', [GatewaysController, 'revision'])
          .as('revision')
          .where('number', router.matchers.number())
        router.get(':id/events', [GatewaysController, 'events']).as('events')
        router.get(':id/pairing', [GatewaysController, 'pairing']).as('pairing')
        router.get(':id/dns', [GatewayNamesController, 'dns']).as('dns')
        router.get(':id/dns/label-names', [GatewayNamesController, 'labelNames']).as('labelNames')
        router
          .group(() => {
            router.patch(':id', [GatewaysController, 'update']).as('update')
            router.post(':id/bind', [GatewaysController, 'bind']).as('bind')
            router.post(':id/refresh', [GatewaysController, 'refresh']).as('refresh')
            router
              .patch(':id/sections/:perchId', [GatewaysController, 'updateSection'])
              .as('updateSection')
            router.post(':id/sections/resolve', [GatewaysController, 'resolve']).as('resolve')
            router.delete(':id/draft', [GatewaysController, 'discardDraft']).as('discardDraft')
            router.post(':id/applies', [GatewaysController, 'createApply']).as('createApply')
            router
              .post(':id/packages', [GatewaysController, 'installPackages'])
              .as('installPackages')
            router.put(':id/sign-key', [GatewaysController, 'setSignKey']).as('setSignKey')
            router.post(':id/pairing', [GatewaysController, 'startPairing']).as('startPairing')
            router
              .post(':id/pairing/confirm', [GatewaysController, 'confirmPairing'])
              .as('confirmPairing')
            router.delete(':id/pairing', [GatewaysController, 'unpair']).as('unpair')
            router.delete(':id/sign-key', [GatewaysController, 'clearSignKey']).as('clearSignKey')
            router
              .post(':id/applies/:applyId/confirm', [GatewaysController, 'confirmApply'])
              .as('confirmApply')
            router
              .post(':id/applies/:applyId/revert', [GatewaysController, 'revertApply'])
              .as('revertApply')
            router
              .post(':id/revisions/:number/restore', [GatewaysController, 'restoreRevision'])
              .as('restoreRevision')
              .where('number', router.matchers.number())
            router
              .post(':id/rejoin/dismiss', [GatewaysController, 'dismissRejoin'])
              .as('dismissRejoin')
            router.post(':id/drift/accept', [GatewaysController, 'acceptDrift']).as('acceptDrift')
            router
              .post(':id/drift/revert-now', [GatewaysController, 'revertDrift'])
              .as('revertDrift')
            router
              .post(':id/enforcement/resume', [GatewaysController, 'resumeEnforcement'])
              .as('resumeEnforcement')
            router.patch(':id/dns', [GatewayNamesController, 'updateDns']).as('updateDns')
            router
              .post(':id/dns/records', [GatewayNamesController, 'createRecord'])
              .as('createRecord')
            router
              .patch(':id/dns/records/:perchId', [GatewayNamesController, 'updateRecord'])
              .as('updateRecord')
            router
              .delete(':id/dns/records/:perchId', [GatewayNamesController, 'deleteRecord'])
              .as('deleteRecord')
            router
              .post(':id/dns/label-names/apply', [GatewayNamesController, 'applyLabelNames'])
              .as('applyLabelNames')
          })
          .use(middleware.requireAdmin())
      })
      .prefix('gateways')
      .as('gateways')
      .where('id', router.matchers.number())
      .use([middleware.auth(), middleware.requirePasswordChange()])
  })
  .prefix('/api/v1')
  .use(middleware.requireSetupComplete())

/**
 * Dashboard. `@adonisjs/static` serves the built files from public/ before
 * the router sees the request; whatever is left that is not an API path gets
 * index.html so the client-side router takes over. Unknown /api/* paths keep
 * the normal JSON 404. Registered last: the router matches in registration
 * order, so the wildcard must come after every API group.
 */
const dashboardIndex = app.publicPath('index.html')
const serveDashboard = async ({ request, response }: HttpContext) => {
  if (request.url().startsWith('/api/')) {
    throw new errors.E_ROUTE_NOT_FOUND([request.method(), request.url()])
  }
  // A built asset the static server did not find is gone, not a page: a tab
  // open across a redeploy asks for the chunks of the build it loaded. A real
  // 404 makes its dynamic import fail cleanly (and the app reload) instead of
  // receiving index.html as "JavaScript".
  if (request.url().startsWith('/assets/')) {
    response.header('Cache-Control', 'no-cache')
    return response.notFound('Not found')
  }
  try {
    await access(dashboardIndex)
  } catch {
    return response.notFound({
      error: 'Dashboard not built. Run `npm run build:dashboard` (the Docker image includes it).',
    })
  }
  response.header('Cache-Control', 'no-cache')
  return response.download(dashboardIndex)
}
router.get('/', serveDashboard)
router.get('*', serveDashboard)
