/*
|--------------------------------------------------------------------------
| Routes file
|--------------------------------------------------------------------------
|
| The routes file is used for defining the HTTP routes.
|
*/

import { access } from 'node:fs/promises'
import { errors } from '@adonisjs/core'
import app from '@adonisjs/core/services/app'
import type { HttpContext } from '@adonisjs/core/http'
import { middleware } from '#start/kernel'
import router from '@adonisjs/core/services/router'
import { controllers } from '#generated/controllers'

/**
 * The setup controller isn't in the auto-generated `controllers` registry
 * yet (regenerated by the dev server on save); declared inline so this
 * routes file remains the source of truth and `npm run typecheck` passes
 * even on a cold checkout.
 */
const SetupController = () => import('#controllers/setup_controller')

/**
 * Same story for the devices controller — added in the poller session.
 * Inline until the next dev-server restart regenerates the registry.
 */
const DevicesController = () => import('#controllers/devices_controller')

/**
 * Settings API lives behind auth + admin and only opens after setup.
 * Inline import for the same generated-registry reason as above.
 */
const SettingsController = () => import('#controllers/settings_controller')
const WifiController = () => import('#controllers/wifi_controller')
const UsersController = () => import('#controllers/users_controller')
const ServicesController = () => import('#controllers/services_controller')
const DestinationsController = () => import('#controllers/destinations_controller')
const UsageController = () => import('#controllers/usage_controller')
const RouterController = () => import('#controllers/router_controller')
const ProfileController = () => import('#controllers/profile_controller')
const DeviceLabelsController = () => import('#controllers/device_labels_controller')
const CollectorsController = () => import('#controllers/collectors_controller')
const ApAgentsController = () => import('#controllers/ap_agents_controller')
const ApJoinTokensController = () => import('#controllers/ap_join_tokens_controller')
const AgentSocketsController = () => import('#controllers/agent_sockets_controller')
const InfraController = () => import('#controllers/infra_controller')

/**
 * Setup wizard endpoints. INTENTIONALLY outside the requireSetupComplete
 * gate (since they ARE the way to complete setup). `status` and `admin` are
 * public; once an admin exists, the rest of the wizard requires that
 * admin's bearer token.
 */
router
  .group(() => {
    router.get('status', [SetupController, 'status']).as('status')
    router.post('admin', [SetupController, 'admin']).as('admin')
    router
      .post('instance', [SetupController, 'instance'])
      .as('instance')
      .use([middleware.auth(), middleware.requireAdmin()])
    router
      .post('collector', [SetupController, 'collector'])
      .as('collector')
      .use([middleware.auth(), middleware.requireAdmin()])
    router
      .get('collector/candidates', [SetupController, 'candidates'])
      .as('collector.candidates')
      .use([middleware.auth(), middleware.requireAdmin()])
    router
      .post('collector/skip', [SetupController, 'skipCollector'])
      .as('collector.skip')
      .use([middleware.auth(), middleware.requireAdmin()])
    router
      .post('collector/:id/adopt', [SetupController, 'adopt'])
      .as('collector.adopt')
      .where('id', router.matchers.number())
      .use([middleware.auth(), middleware.requireAdmin()])
  })
  .prefix('/api/v1/setup')
  .as('setup')

/**
 * Collector self-announcement. INTENTIONALLY outside both `auth` and the
 * requireSetupComplete gate — a router that boots before the wizard has been
 * run must still be able to show up. Everything an announce can do is create
 * or refresh ONE `pending` row; adoption is an explicit admin action under
 * /api/v1/settings/collectors. Declared next to the setup group (outside the
 * gate for the same reason) and before the /api/v1 group so registration
 * order never lets the SPA wildcard at the bottom of this file swallow it.
 */
router
  .post('/api/v1/collectors/announce', [CollectorsController, 'announce'])
  .as('collectors.announce')

/**
 * ap-controller join (docs/ap-controller.md section 2.1). Outside `auth` and
 * the setup gate for the same reason as the announce: the join token in the
 * body is the credential.
 */
router.post('/api/v1/ap-agent/join', [ApAgentsController, 'join']).as('apAgent.join')

/**
 * The device agents' WebSockets. providers/agent_gateway_provider.ts handles
 * the upgrades on the Node server; these routes only see what it does not:
 * an upgrade in the moment after start, before it is attached (503, so the
 * agent retries in seconds instead of backing off for minutes on a 404), and
 * plain GETs (426).
 */
router.get('/api/v1/ap-agent/ws', [AgentSocketsController, 'fallback']).as('apAgent.wsFallback')
router
  .get('/api/v1/collector-agent/ws', [AgentSocketsController, 'fallback'])
  .as('collectorAgent.wsFallback')

/**
 * Normal API surface. Gated behind requireSetupComplete so /auth/login and
 * /account/* return a structured 503 with the next wizard step while the
 * instance hasn't been bootstrapped yet.
 */
router
  .group(() => {
    router
      .group(() => {
        router.post('signup', [controllers.NewAccount, 'store'])
        router.post('login', [controllers.AccessTokens, 'store'])
      })
      .prefix('auth')
      .as('auth')

    router
      .group(() => {
        router.get('profile', [controllers.Profile, 'show'])
        router.patch('password', [ProfileController, 'changePassword'])
        router.post('logout', [controllers.AccessTokens, 'destroy'])
      })
      .prefix('account')
      .as('profile')
      .use(middleware.auth())

    router
      .group(() => {
        router.get('hostname-enrichment', [SettingsController, 'hostnameEnrichment'])
        router.patch('hostname-enrichment', [SettingsController, 'updateHostnameEnrichment'])
        router.get('hostname-enrichment/sources', [SettingsController, 'hostnameEnrichmentSources'])
        router.get('presence', [SettingsController, 'presence']).as('presence')
        router.patch('presence', [SettingsController, 'updatePresence']).as('updatePresence')
        router.get('wifi-sources', [SettingsController, 'wifiSources'])
        router.post('wifi-sources/probe', [SettingsController, 'probeWifiSourceDraft'])
        router.post('wifi-sources', [SettingsController, 'createWifiSource'])
        router.put('wifi-sources/:id', [SettingsController, 'updateWifiSource'])
        router.delete('wifi-sources/:id', [SettingsController, 'deleteWifiSource'])
        router.post('wifi-sources/:id/probe', [SettingsController, 'probeWifiSource'])
        router
          .post('wifi-sources/:id/agent/ping', [ApAgentsController, 'ping'])
          .as('wifiSources.agentPing')
        router
          .delete('wifi-sources/:id/agent', [ApAgentsController, 'forget'])
          .as('wifiSources.agentForget')

        router.get('ap-join-tokens', [ApJoinTokensController, 'index']).as('apJoinTokens.index')
        router.post('ap-join-tokens', [ApJoinTokensController, 'store']).as('apJoinTokens.store')
        router
          .post('ap-join-tokens/:id/reveal', [ApJoinTokensController, 'reveal'])
          .as('apJoinTokens.reveal')
        router
          .delete('ap-join-tokens/:id', [ApJoinTokensController, 'destroy'])
          .as('apJoinTokens.destroy')
        router.get('ap-agent/install', [ApAgentsController, 'installInfo']).as('apAgent.install')

        router.get('collectors', [CollectorsController, 'index']).as('collectors.index')
        router.post('collectors', [CollectorsController, 'store']).as('collectors.store')
        /**
         * Static segments declared before the `:id` routes, same reason as
         * `labels` in the devices group below.
         */
        router
          .get('collectors/discovery', [CollectorsController, 'discovery'])
          .as('collectors.discovery')
        router
          .patch('collectors/discovery', [CollectorsController, 'updateDiscovery'])
          .as('collectors.updateDiscovery')
        router
          .post('collectors/probe', [CollectorsController, 'probeDraft'])
          .as('collectors.probeDraft')
        router.put('collectors/:id', [CollectorsController, 'update']).as('collectors.update')
        router.delete('collectors/:id', [CollectorsController, 'destroy']).as('collectors.destroy')
        router.post('collectors/:id/probe', [CollectorsController, 'probe']).as('collectors.probe')
        router.post('collectors/:id/adopt', [CollectorsController, 'adopt']).as('collectors.adopt')
        router
          .post('collectors/:id/dismiss', [CollectorsController, 'dismiss'])
          .as('collectors.dismiss')

        router.get('users', [UsersController, 'index']).as('users.index')
        router.post('users', [UsersController, 'store']).as('users.store')
        router.patch('users/:id/role', [UsersController, 'updateRole']).as('users.updateRole')
        router.delete('users/:id', [UsersController, 'destroy']).as('users.destroy')
      })
      .prefix('settings')
      .as('settings')
      .use([middleware.auth(), middleware.requirePasswordChange(), middleware.requireAdmin()])

    /**
     * Read API for what the poller has captured. All three endpoints are
     * behind `auth` (operator and admin both qualify) so the eventual
     * dashboard can call them with a logged-in user's bearer token
     * without needing service tokens.
     */
    router
      .get('traffic', [DevicesController, 'aggregateTraffic'])
      .as('aggregateTraffic')
      .use([middleware.auth(), middleware.requirePasswordChange()])
    router
      .get('traffic/top', [DevicesController, 'topTraffic'])
      .as('topTraffic')
      .use([middleware.auth(), middleware.requirePasswordChange()])
    router
      .get('protocols', [DevicesController, 'aggregateProtocols'])
      .as('aggregateProtocols')
      .use([middleware.auth(), middleware.requirePasswordChange()])
    router
      .get('protocols/:protocol/devices', [DevicesController, 'aggregateProtocolDevices'])
      .as('aggregateProtocolDevices')
      .use([middleware.auth(), middleware.requirePasswordChange()])
    /**
     * Network-wide "where is the traffic going": top peer IPs (and their
     * ASNs) across every device over a window, from the hourly peer history.
     */
    router
      .get('peers/top', [DevicesController, 'topPeers'])
      .as('topPeers')
      .use([middleware.auth(), middleware.requirePasswordChange()])
    /**
     * "How many GB did my servers push": bytes served per TLS SNI / HTTP
     * Host, from the hourly service history the collector's nDPI path feeds.
     */
    router
      .group(() => {
        router.get('', [ServicesController, 'index']).as('index')
        router.get(':serverName/traffic', [ServicesController, 'traffic']).as('traffic')
      })
      .prefix('services')
      .as('services')
      .use([middleware.auth(), middleware.requirePasswordChange()])

    router
      .get('router', [RouterController, 'index'])
      .as('router')
      .use([middleware.auth(), middleware.requirePasswordChange()])

    /**
     * Collector picker for any signed-in user. The settings list above is
     * admin-only and carries the pollable address; this one is the thin,
     * address-free shape an operator may see.
     */
    router
      .get('collectors', [CollectorsController, 'summary'])
      .as('collectors')
      .use([middleware.auth(), middleware.requirePasswordChange()])

    router
      .group(() => {
        router.get('', [UsageController, 'index']).as('index')
        router.get('intervals', [UsageController, 'intervals']).as('intervals')
      })
      .prefix('usage')
      .as('usage')
      .use([middleware.auth(), middleware.requirePasswordChange()])

    router
      .group(() => {
        router.get('', [DestinationsController, 'index']).as('index')
        router.get(':serverName/traffic', [DestinationsController, 'traffic']).as('traffic')
      })
      .prefix('destinations')
      .as('destinations')
      .use([middleware.auth(), middleware.requirePasswordChange()])

    router
      .group(() => {
        router.get('', [DevicesController, 'index']).as('index')
        /**
         * Operator-supplied names, types, tags and notes. `labels` is a
         * static segment and is declared before the `:mac/…` routes so it
         * can never be read as a MAC. Writes are open to any signed-in
         * user, like the reads around them.
         */
        router.get('labels', [DeviceLabelsController, 'index']).as('labels')
        router.get(':mac/label', [DeviceLabelsController, 'show']).as('label')
        router.patch(':mac/label', [DeviceLabelsController, 'update']).as('updateLabel')
        router.delete(':mac/label', [DeviceLabelsController, 'destroy']).as('destroyLabel')
        router.get(':mac/traffic', [DevicesController, 'traffic']).as('traffic')
        router.get(':mac/peers', [DevicesController, 'peers']).as('peers')
        router.get(':mac/peers/history', [DevicesController, 'peersHistory']).as('peersHistory')
        router.get(':mac/services', [ServicesController, 'device']).as('services')
        router.get(':mac/destinations', [DestinationsController, 'device']).as('destinations')
        router.get(':mac/overview', [DevicesController, 'overview']).as('overview')
        router.get(':mac/presence', [DevicesController, 'presence']).as('presence')
        router.get(':mac/protocols', [DevicesController, 'protocols']).as('protocols')
      })
      .prefix('devices')
      .as('devices')
      .use([middleware.auth(), middleware.requirePasswordChange()])

    router
      .group(() => {
        router.get('overview', [WifiController, 'overview'])
        router.get('ssids', [WifiController, 'ssids'])
        router.get('ssids/:ssid/clients', [WifiController, 'ssidClients'])
        router.get('ssids/:ssid/throughput', [WifiController, 'ssidThroughput'])
        router.get('clients', [WifiController, 'clients'])
        router.get('clients/history', [WifiController, 'clientsHistory'])
        router.get('clients/:mac', [WifiController, 'client'])
        router.get('clients/:mac/signal', [WifiController, 'clientSignal'])
        router.get('rf', [WifiController, 'rf'])
        router.get('rf/history', [WifiController, 'rfHistory'])
        router.get('aps', [WifiController, 'aps'])
        router.get('aps/throughput', [WifiController, 'apsThroughput'])
        router.get('aps/:id/health', [WifiController, 'apHealth'])
        router
          .group(() => {
            router.post('clients/:mac/kick', [WifiController, 'kickClient'])
            router.post('clients/:mac/steer', [WifiController, 'steerClient'])
            router.post('aps/:id/reboot', [WifiController, 'rebootAp'])
            router.post('aps/:id/locate', [WifiController, 'locateAp'])
          })
          .use(middleware.requireAdmin())
      })
      .prefix('wifi')
      .as('wifi')
      .use([middleware.auth(), middleware.requirePasswordChange()])

    /**
     * Infrastructure view (docs/infrastructure-view.md section 7): the network
     * map's devices, ports and cables. Any signed-in user reads it; the layout
     * is shared work, so every write is admin-only.
     */
    router
      .group(() => {
        router.get('layout', [InfraController, 'layout']).as('layout')
        router.get('state', [InfraController, 'state']).as('state')
        router
          .group(() => {
            router.post('nodes', [InfraController, 'createNode']).as('nodes.store')
            router
              .patch('nodes/:id', [InfraController, 'updateNode'])
              .as('nodes.update')
              .where('id', router.matchers.number())
            router
              .delete('nodes/:id', [InfraController, 'destroyNode'])
              .as('nodes.destroy')
              .where('id', router.matchers.number())
            router
              .post('nodes/:id/bind', [InfraController, 'bindNode'])
              .as('nodes.bind')
              .where('id', router.matchers.number())
            router
              .post('nodes/:id/ports', [InfraController, 'addPorts'])
              .as('nodes.ports.store')
              .where('id', router.matchers.number())
            router
              .patch('ports/:id', [InfraController, 'updatePort'])
              .as('ports.update')
              .where('id', router.matchers.number())
            router
              .delete('ports/:id', [InfraController, 'destroyPort'])
              .as('ports.destroy')
              .where('id', router.matchers.number())
            router.post('links', [InfraController, 'createLink']).as('links.store')
            router
              .patch('links/:id', [InfraController, 'updateLink'])
              .as('links.update')
              .where('id', router.matchers.number())
            router
              .delete('links/:id', [InfraController, 'destroyLink'])
              .as('links.destroy')
              .where('id', router.matchers.number())
            router.put('positions', [InfraController, 'savePositions']).as('positions')
          })
          .use(middleware.requireAdmin())
      })
      .prefix('infra')
      .as('infra')
      .use([middleware.auth(), middleware.requirePasswordChange()])
  })
  .prefix('/api/v1')
  .use(middleware.requireSetupComplete())

/**
 * Dashboard. `@adonisjs/static` serves the built files from public/ before
 * the router sees the request; whatever is left that is not an API path gets
 * index.html so the client-side router takes over. Unknown /api/* paths keep
 * the normal JSON 404. Registered last: the router matches in registration
 * order, so the wildcard must come after every API group.
 */
const dashboardIndex = app.publicPath('index.html')
const serveDashboard = async ({ request, response }: HttpContext) => {
  if (request.url().startsWith('/api/')) {
    throw new errors.E_ROUTE_NOT_FOUND([request.method(), request.url()])
  }
  // A built asset the static server did not find is gone, not a page: a tab
  // open across a redeploy asks for the chunks of the build it loaded. A real
  // 404 makes its dynamic import fail cleanly (and the app reload) instead of
  // receiving index.html as "JavaScript".
  if (request.url().startsWith('/assets/')) {
    response.header('Cache-Control', 'no-cache')
    return response.notFound('Not found')
  }
  try {
    await access(dashboardIndex)
  } catch {
    return response.notFound({
      error: 'Dashboard not built. Run `npm run build:dashboard` (the Docker image includes it).',
    })
  }
  response.header('Cache-Control', 'no-cache')
  return response.download(dashboardIndex)
}
router.get('/', serveDashboard)
router.get('*', serveDashboard)
